#!/usr/bin/python3

import re, os, sys, pysrt, chardet, logging
from sys import exit

ADS = ['.*a Card Shark AMERICASCARDROOM.*',
       '.*OpenSubtitles.*',
       '.*Advertise your product or brand here.*',
       '.*Apóyanos y conviértete en miembro VIP Para.*',
       '.*Addic7ed.*',
       '.*argenteam.*',
       '.*AllSubs.*',
       'Created and Encoded by.*',
       '.*corrected.*by.*',
       '.*Entre a AmericasCardroom. com Hoy.*',
       '.*Everyone is intimidated by a shark. Become.*',
       '.*Juegue Poker en Línea por Dinero Real.*',
       '.*OpenSubtitles.*',
       '.*Open Subtitles.*',
       '.*MKV Player.*',
       '.*MKV player.*',
       '.*Resync.*for.*',
       '.*Resync.*improved.*',
       '.*Ripped?By.*',
       '.*Sigue "Community" en.*',
       '.*Subtitles.*by.*',
       '.*Subt?tulos.*por.*',
       '.*Support us and become VIP member.*',
       '.*Subs.*Team.*',
       '.*subscene.*',
       '.*Subtitulado por.*',
       '.*subtitulamos.*',
       '.*Synchronized.*by.*',
       '.*Sincronizado y corregido por.*',
       '.*subdivx.*',
       '.*Sync.*Corrected.*',
       '.*Sync.*corrections.*by.*',
       '.*sync and corrections by.*'
       '.*Sync.*by.*',
       '.*Una.*traducci?n.*de.*',
       '.*tvsubtitles.*',
       '.*Una.*traducci?n.*de.*',
       'Tacho8',
       '.*www. com.*',
       '.*www. link.*',
       '.*www. es.*'
]

def ads_in_line(line):
    for pt in ADS:
        if re.match(pt, line, re.DOTALL):
            log.info('true')
            return True
    return False

# Setup logger
log_filename = os.path.join(os.path.dirname(sys.argv[0]), 'subscleaner.log')
logging.basicConfig(
    filename=log_filename,
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s - %(message)s'
)
log = logging.getLogger("Subscleaner")

if __name__ == '__main__':
    from sys import argv
    from shutil import move

    if '-h' in argv or len(argv) == 1:
        log.error('Usage: subscleaner.py <sub1> <sub2> <sub3> <...>')
        exit()

    for filename in argv[1:]:
        log.error("Analyzing:", filename)
        with open(filename, 'rb') as f:
            encoding = chardet.detect(f.read())
        encoding = encoding['encoding']
        subs = pysrt.open(filename, encoding=encoding)
        modified = False
        for i, line in enumerate(subs):
            if ads_in_line(line.text):
                log.error("Removing: " + str(line) + " on file " + filename + "\n")
                del subs[i]
                modified = True
        if modified:
            subs.save(filename)
